[extension]
name = "vogui"
include = [
  "js/dist",
]

[extension.native]
path = "rust/target/{profile}/libvo_vogui"

[[extension.native.targets]]
target = "aarch64-apple-darwin"
library = "libvo_vogui.dylib"

[[extension.native.targets]]
target = "x86_64-unknown-linux-gnu"
library = "libvo_vogui.so"

[[extension.native.targets]]
target = "x86_64-pc-windows-msvc"
library = "vo_vogui.dll"

[extension.wasm]
type = "standalone"
wasm = "vogui.wasm"
local_wasm = "web-artifacts/vogui.wasm"

[extension.web.js]
renderer = "js/dist/studio_renderer.js"
protocol = "js/dist/studio_protocol.js"
host_bridge = "js/dist/studio_host_bridge.js"
